[program:k3s-server]
command=/usr/local/bin/k3s server \
  --write-kubeconfig-mode=644 \
  --disable traefik \
  --snapshotter native \
  --cluster-init
directory=/
user=root
autostart=true
autorestart=true
startsecs=10
startretries=5
stderr_logfile=/var/log/k3s-server.err.log
stdout_logfile=/var/log/k3s-server.out.log
stdout_logfile_maxbytes=10MB
stopsignal=INT
stopwaitsecs=10
priority=1
